import Footer from "@/components/footer";
import Header from "@/components/header";
import Head from "next/head";
import Link from "next/link";

export default function ContactSalesAllInOne() {
  return (
    <>
      <Head>
        <title>LIVE PROXIES | CONTACT SALES ALL IN ONE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="contact_sales_page_wrapper home_page_wrapper">
      <Header />
      <section>
        <div className="container contact_sales_all_con">
          <div className="col-lg-6 col-md-6 col-sm-12 col-xs-12 contact_sales_sub_con1">
            <h2>
              <span>Submit</span> a request
            </h2>
            <h3>
              Our team is happy to answer your sales questions. Fill out the
              form and we’ll be in touch as soon as possible.
            </h3>
            <div></div>
          </div>
          <div className="col-lg-6 col-md-6 col-sm-12 col-xs-12 contact_sales_sub_con2">
            <form action="" className="sign_in_reg_form text-center">
              <input
                type="text"
                placeholder="Full name*"
                className="reg-form-control"
                required
              />
              <br />
              <input
                type="text"
                placeholder="Company name (Optional)"
                className="reg-form-control"
                required
              />
              <br />
              <input
                type="text"
                placeholder="Work email address*"
                className="reg-form-control"
                required
              />
              <br />
              <textarea
                type="text"
                placeholder="Please describe your use case and needs*"
                required
              ></textarea>
              <br />
              <Link href="/">
                <button type="submit">Contact sales</button>
              </Link>
            </form>
          </div>
        </div>
      </section>

      <Footer />
      </div>
    </>
  );
}
