import Footer from "@/components/footer";
import Header from "@/components/header";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import $ from "jquery";
import Questions from "@/components/questions";
export default function ContactUs() {
  return (
    <>
      <Head>
        <title>Contact us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home_page_wrapper contact_us_page_wrapper custom-pricing_page_wrapper">
        <Header />
        <section>
          <div className="container custom_pricing_main_con text-center">
            <h2>
              All In One <span>Custom</span> Solution
            </h2>
            <h3>
              Scale your operations by working with the most reliable proxy
              network to get the enterprise level solution you need.
            </h3>
            <div>
              <h4>You couldn’t find what you need?</h4>
              <h5>
                Our proxies are known for their reliability and quality,
                ensuring a smooth and seamless experience for your business. We
                are dedicated to providing the best service and support to help
                you achieve your goals.
              </h5>
              <a href="/contact-sales-all-in-one.html">
                Contact sales{" "}
                <img src="/images/contact-us-blue-arrow-up-right.svg" />
              </a>
            </div>
          </div>
        </section>

        <Questions />
      </div>
      <Footer />
    </>
  );
}
