import Analytics from "@/modules/dashboard/analytics";
import Authorization from "@/modules/dashboard/authorization";
import History from "@/modules/dashboard/history";
import Home from "@/modules/dashboard/home";
import Notification from "@/modules/dashboard/notifications";
import SideBar from "@/modules/dashboard/sidebar";
import YourIpAddress from "@/modules/dashboard/you_ip_address";
import Head from "next/head";
import { useState } from "react";

export default function Dashboard(props) {
  const [tab, setTab] = useState(0);

  return (
    <>
      <Head>
        <title>LIVE PROXIES | DASHBOARD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="/snap.js"></script>
      </Head>
      <div className="dashboard_page_wrapper home_page_wrapper">
        <div className="dashboard_gene_main_con">
          <YourIpAddress />
          <SideBar setTab={setTab} tab={tab} />

          <div className="home-section-con col-lg-10 col-md-9 col-sm-9 col-xs-9">
            {tab == 0 && <Home setTab={setTab} />}
            {tab == 1 && <History />}
            {tab == 2 && <Notification />}
            {tab == 3 && <Analytics />}
            {tab == 4 && <Authorization />}
          </div>
        </div>
      </div>
    </>
  );
}
