import Footer from "@/components/footer";
import Header from "@/components/header";
import Questions from "@/components/questions";
import SimpleManagementDashboard from "@/modules/home/ simple_management_dashboard";
import GetSolutions from "@/modules/home/get_solution";
import LiveToday from "@/modules/home/live_today";
import Plans from "@/modules/home/plans";
import UtilizeFavouriteApp from "@/modules/home/utilize_favorite_app";
import WhyLiveProxies from "@/modules/home/why_live_proxies";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section>
        <div class="hero_img text-center">
          <div class="hero_img_text_con">
            <h2>OFTEN IMITATED | NEVER DUPLICATED</h2>
            <h3>
              Enjoy the reassurance of entirely private, unique, and dedicated
              proxies.
            </h3>
            <Link href="/sign-up">Create your account</Link>
          </div>
        </div>
      </section>

      <section>
        <div class="container the_most_realiable_main_con text-center">
          <Link href="/#!">
            <img
              src="/images/the-most-realiable-trust-pilot-icon.png"
              class="the_most_realiable_trust_pilot_icon"
            />
          </Link>
          <h2>
            The most <span>reliable</span> proxy network
          </h2>
          <h3>
            Here at Live, we provide unique, stable, and unblocked proxies for
            any use case or site. We work diligently to make sure our proxies
            meet your expectations.
          </h3>
          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <img src="/images/the-most-realiable-house-ips.svg" />
            <h4>Rotating Residential IPs</h4>
            <h5>
              Leverage your experience with our anonymous, real-peer rotating
              residential proxies.
            </h5>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <img src="/images/the-most-realiable-static-ips.svg" />
            <h4>Static Residential IPs</h4>
            <h5>
              Enjoy keeping the same residential IPs for 30 days or longer.
            </h5>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <img src="/images/the-most-realiable-mobile-ips.svg" />
            <h4>Rotating Mobile IPs</h4>
            <h5>
              Have the liberty of becoming a mobile user with our stable mobile
              IPs.
            </h5>
          </div>
        </div>
      </section>
      <section>
        <div class="top_use_cases_main_con top_use_cases_first_main_con container text-center">
          <h2>
            Top use <span>cases</span>
          </h2>
          <h3>
            Scrape data anonymously and access content in any geo-location
          </h3>
          <div class="tile" id="tile-1">
            <ul class="nav nav-tabs text-center nav-justified" role="tablist">
              <li class="nav-item">
                <Link
                  class="nav-link top_use_cases_slider_selector_base case_trends_bigger_chart_stats_btn_selectors active"
                  id="ecommerce-tab"
                  data-toggle="tab"
                  href="#ecommerce"
                >
                  eCommerce
                </Link>
              </li>
              <li class="nav-item">
                <Link
                  class="nav-link top_use_cases_slider_selector_base case_trends_bigger_chart_stats_btn_selectors"
                  id="smm-tab"
                  data-toggle="tab"
                  href="#smm"
                >
                  SMM
                </Link>
              </li>
              <li class="nav-item">
                <Link
                  class="nav-link top_use_cases_slider_selector_base case_trends_bigger_chart_stats_btn_selectors"
                  id="market_research-tab"
                  data-toggle="tab"
                  href="#market_research"
                >
                  Market Research
                </Link>
              </li>
              <li class="nav-item top_use_cases_nft_icon">
                <Link
                  class="nav-link top_use_cases_slider_selector_base case_trends_bigger_chart_stats_btn_selectors"
                  id="esports-tab"
                  data-toggle="tab"
                  href="#nft"
                >
                  NFT
                </Link>
              </li>
              <li class="nav-item">
                <Link
                  class="nav-link top_use_cases_slider_selector_base case_trends_bigger_chart_stats_btn_selectors"
                  id="esports-tab"
                  data-toggle="tab"
                  href="#esports"
                >
                  Gaming
                </Link>
              </li>
              <li class="nav-item">
                <Link
                  class="nav-link top_use_cases_slider_selector_base case_trends_bigger_chart_stats_btn_selectors"
                  id="seoserp-tab"
                  data-toggle="tab"
                  href="#seoserp"
                >
                  SEO/SERP
                </Link>
              </li>
              <li class="nav-item">
                <Link
                  class="nav-link top_use_cases_slider_selector_base case_trends_bigger_chart_stats_btn_selectors"
                  id="adtech-tab"
                  data-toggle="tab"
                  href="#addtech"
                >
                  AdTech
                </Link>
              </li>
              <div class="top_use_cases_slider"></div>
            </ul>
            <div class="tab-content text-center">
              <div class="tab-pane active" id="ecommerce">
                <div class="container top_use_content_con">
                  <div class="top_use_content_img_con col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div></div>
                  </div>
                  <div class="ecommerce_inner_slider">
                    <div class="slide">
                      <img src="/images/top-use-cases-e-maps-img-clothes-and-sneakers.svg" />
                    </div>
                    <div class="slide">
                      <img src="/images/top-use-cases-e-maps-img-computer.svg" />
                    </div>
                    <div class="slide">
                      <img src="/images/top-use-cases-e-maps-img-basket-ball-cards.svg" />
                    </div>
                  </div>
                  <div class="top_use_content_text_con col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <h2>Outshine the competitors with web data</h2>
                    <h4>
                      Optimize your pricing strategy and manage your inventory
                      efficiently by acquiring valuable insights on your
                      competition, products, and markets. Automate tasks and
                      streamline operations to save time and minimize resources.
                    </h4>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="smm">
                <div class="container top_use_content_con">
                  <div class="top_use_content_img_con col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div></div>
                  </div>
                  <div class="top_use_content_text_con col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <h2>
                      The highest quality media proxies for all your needs
                    </h2>
                    <h4>
                      Unlock the full potential of your social media strategy by
                      staying on top of trends and knowing what your customers
                      and audiences want. Enhance your data collection and
                      social listening capabilities to stay ahead of the
                      competition and reach new markets.
                    </h4>
                    <div>
                      <li>
                        <Link href="/#!"></Link>
                      </li>
                      <li>
                        <Link href="/#!"></Link>
                      </li>
                      <li>
                        <Link href="/#!"></Link>
                      </li>
                      <li>
                        <Link href="/#!"></Link>
                      </li>
                    </div>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="market_research">
                <div class="container top_use_content_con">
                  <div class="top_use_content_img_con col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div></div>
                  </div>
                  <div class="top_use_content_text_con col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <h2>Increase and speed up your research</h2>
                    <h4>
                      Unlock global market insights, bypass IP restrictions, and
                      predict trends by swiftly gathering data with Live
                      Proxies. With a comprehensive market research, you can
                      know your customers and target audience better helping you
                      stay ahead of the competition.
                    </h4>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="nft">
                <div class="container top_use_content_con">
                  <div class="top_use_content_img_con col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <div></div>
                  </div>
                  <div class="top_use_content_text_con col-lg-9 col-md-8 col-sm-8 col-xs-12">
                    <h2>Increase your chance of buying the NFT you want</h2>
                    <h4>
                      Get past strict proxy restrictions and automate your NFT
                      tasks from creating multiple accounts to going for limited
                      releases. Furthermore, effortlessly scrape data to collect
                      information on NFT prices, sales, and trends, as well as
                      monitor NFTs.
                    </h4>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="esports">
                <div class="container top_use_content_con">
                  <div class="top_use_content_img_con col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div></div>
                  </div>
                  <div class="top_use_content_text_con col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <h2>Create multiple accounts & unlock games</h2>
                    <h4>
                      Enhance your gaming experience by bypassing geographical
                      restrictions and IP blocks while on an anonymous
                      connection. Advance in your game by completing all game
                      levels and using your software with our proxies to keep
                      your account protected.
                    </h4>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="seoserp">
                <div class="container top_use_content_con">
                  <div class="top_use_content_img_con col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div></div>
                  </div>
                  <div class="top_use_content_text_con col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <h2>Easy handle of everyday search optimization</h2>
                    <h4>
                      Scrape SERP and build backlinks to conduct keyword
                      research, gather rankings data, and analyze competition
                      and consumer trends. Additionally, avoid bans and search
                      keywords from different geographical locations to help
                      reach the right audience.
                    </h4>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="addtech">
                <div class="container top_use_content_con">
                  <div class="top_use_content_img_con col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div></div>
                  </div>
                  <div class="top_use_content_text_con col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <h2>Maximize every ads dollar for AdTech</h2>
                    <h4>
                      Verify your ads meet your expectations and are clear of
                      fraudulent or harmful activity without getting detected to
                      help protect your brand image. Maximize your ad campaigns
                      by easily testing and monitoring them with no issues.
                    </h4>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section>
        <div class="honest_price_no_surprises_main_con">
          <div class="container">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 honest_price_no_surprises_main_text_con">
              <div class="honest_price_no_surprises_main_text_inner_con">
                <Link href="/#!">
                  <img src="/images/honest-price-what-we-offer-trust-pilot-icon.svg" />
                </Link>
                <h2>
                  <span>Trusted Service</span> with full transparency
                </h2>
                <h4>
                  Our provision has proven itself to thousands of satisfied
                  users, and your account will inform you with all necessary
                  details about your proxies at no additional cost.
                </h4>
                <Link href="/sign-up.html">Create your account</Link>
              </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 honest_price_no_surprises_main_img_con">
              <div class="sliderContainer">
                <div class="progress_bar_main_con">
                  <h1>What we offer</h1>
                  <h2>
                    With a variety of options, select the plan that best suits
                    your needs
                  </h2>
                  <div class="progressBarContainer">
                    <div>
                      <h3>Residential</h3>
                      <h4>Rotating</h4>
                      <span data-slick-index="0" class="progressBar"></span>
                    </div>
                    <div>
                      <h3>Residential</h3>
                      <h4>Static</h4>
                      <span data-slick-index="1" class="progressBar"></span>
                    </div>
                    <div>
                      <h3>Mobile</h3>
                      <h4>Rotating</h4>
                      <span data-slick-index="2" class="progressBar"></span>
                    </div>
                  </div>
                </div>
                <div class="slider single-item">
                  <div class="slide1">
                    <div class="what_we_offer_meter_unmeter_con top_use_cases_main_con container text-center">
                      <div class="tile" id="tile-1">
                        <ul
                          class="nav metered_resid_rotate_nav-tabs metered_unmetered_nav-tabs text-center nav-justified"
                          role="tablist"
                        >
                          <li class="nav-item">
                            <Link
                              class="nav-link case_trends_bigger_chart_stats_btn_selectors active"
                              id="metered-tab"
                              data-toggle="tab"
                              href="#metered"
                            >
                              Metered
                            </Link>
                          </li>
                          <li class="nav-item">
                            <Link
                              class="nav-link case_trends_bigger_chart_stats_btn_selectors"
                              id="unmetered-tab"
                              data-toggle="tab"
                              href="#unmetered"
                            >
                              Unmetered
                            </Link>
                          </li>
                          <div class="top_use_cases_slider"></div>
                        </ul>
                        <div class="tab-content text-center">
                          <div class="tab-pane active" id="metered">
                            <div class="container top_use_content_con">
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-us-icon.svg" />
                                <h2>United States</h2>
                                <h6>State proxies offered separately</h6>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$70.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-ca-icon.svg" />
                                <h2>Canada</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$70.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-gb-icon.svg" />
                                <h2>United Kingdom</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$70.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-ww-icon.svg" />
                                <h2>Random Location</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$70.00</h4>
                                <h5>per plan</h5>
                              </div>
                            </div>
                          </div>
                          <div class="tab-pane fade" id="unmetered">
                            <div class="container top_use_content_con">
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-us-icon.svg" />
                                <h2>United States</h2>
                                <h6>State proxies offered separately</h6>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$120.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-ca-icon.svg" />
                                <h2>Canada</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$120.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-gb-icon.svg" />
                                <h2>United Kingdom</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$120.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-ww-icon.svg" />
                                <h2>Random Location</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$120.00</h4>
                                <h5>per plan</h5>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="slide2">
                    <div class="what_we_offer_meter_unmeter_con top_use_cases_main_con container text-center">
                      <div class="tile" id="tile-1">
                        <ul
                          class="nav metered_resid_static_nav-tabs metered_unmetered_nav-tabs text-center nav-justified"
                          role="tablist"
                        >
                          <li class="nav-item">
                            <Link
                              class="nav-link active"
                              id="metered-tab"
                              data-toggle="tab"
                              href="#metered_resid_static"
                            >
                              Metered
                            </Link>
                          </li>
                          <li class="nav-item">
                            <Link
                              class="nav-link"
                              id="unmetered-tab"
                              data-toggle="tab"
                              href="#unmetered_resid_static"
                            >
                              Unmetered
                            </Link>
                          </li>
                          <div class="top_use_cases_slider"></div>
                        </ul>
                        <div class="tab-content text-center">
                          <div
                            class="tab-pane active"
                            id="metered_resid_static"
                          >
                            <div class="container top_use_content_con">
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-us-icon.svg" />
                                <h2>United States</h2>
                                <h6>State proxies offered separately</h6>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$35.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-ca-icon.svg" />
                                <h2>Canada</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$35.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-gb-icon.svg" />
                                <h2>United Kingdom</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$35.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-ww-icon.svg" />
                                <h2>Random Location</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$35.00</h4>
                                <h5>per plan</h5>
                              </div>
                            </div>
                          </div>
                          <div
                            class="tab-pane fade"
                            id="unmetered_resid_static"
                          >
                            <div class="container top_use_content_con">
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-us-icon.svg" />
                                <h2>United States</h2>
                                <h6>State proxies offered separately</h6>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$97.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-ca-icon.svg" />
                                <h2>Canada</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$97.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-gb-icon.svg" />
                                <h2>United Kingdom</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$97.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-ww-icon.svg" />
                                <h2>Random Location</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$97.00</h4>
                                <h5>per plan</h5>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="slide3">
                    <div class="what_we_offer_meter_unmeter_con top_use_cases_main_con container text-center">
                      <div class="tile" id="tile-1">
                        <ul
                          class="nav metered_mobile_rotat_nav-tabs metered_unmetered_nav-tabs text-center nav-justified"
                          role="tablist"
                        >
                          <li class="nav-item">
                            <Link
                              class="nav-link active"
                              id="metered-tab"
                              data-toggle="tab"
                              href="#metered_mobile_rotat"
                            >
                              Metered
                            </Link>
                          </li>
                          <div class="top_use_cases_slider"></div>
                        </ul>
                        <div class="tab-content text-center">
                          <div
                            class="tab-pane active"
                            id="metered_mobile_rotat"
                          >
                            <div class="container top_use_content_con">
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-us-icon.svg" />
                                <h2>United States</h2>
                                <h6>State proxies offered separately</h6>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$62.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-ca-icon.svg" />
                                <h2>Canada</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$62.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-gb-icon.svg" />
                                <h2>United Kingdom</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$62.00</h4>
                                <h5>per plan</h5>
                              </div>
                              <span></span>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3 what_we_offer_meter_unmeter_flag_con">
                                <img src="/images/honest-price-what-we-offer-ww-icon.svg" />
                                <h2>Random Location</h2>
                              </div>
                              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-9 what_we_offer_meter_unmeter_price_con">
                                <h3>Starts from</h3>
                                <h4>$62.00</h4>
                                <h5>per plan</h5>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <WhyLiveProxies />
	  <Plans />
      <GetSolutions />
      <SimpleManagementDashboard />
      <UtilizeFavouriteApp />
      <Questions />
      <LiveToday />
      <Footer />
    </>
  );
}
