import Footer from "@/components/footer";
import Header from "@/components/header";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import $ from "jquery";
import Questions from "@/components/questions";
export default function RotatingMobileProxiesPricing() {
  return (
    <>
      <Head>
        <title>LIVE PROXIES | ROTATING RESIDENTIAL PROXIES PRICING</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="rotat_mobile_prox_pric_page_wrapper rotat_resid_prox_pric_page_wrapper home_page_wrapper custom-pricing_page_wrapper">
        <Header />
        <section>
          <div className="container rotat_resid_prox_pric_main_con text-center">
            <div className="container rotat_resid_prox_pric_headline_con text-center">
              <h2>
                <span>Rotating Mobile</span> Proxies Pricing
              </h2>
              <h3>
                Maintain optimal performance by switching to fresh IPs after a
                certain time period without changing your set of proxies.
              </h3>
            </div>
            <div className="live_proxies_plan_table_main_con">
              <div className="live_proxies_plan_table_sub_con2">
                <input
                  type="radio"
                  onChange={() => {}}
                  className="tab-toggle"
                  name="tab-toggle-rotating"
                  id="tab1"
                  checked
                />
                <input
                  type="radio"
                  className="tab-toggle"
                  name="tab-toggle-rotating"
                  id="tab2"
                />
                <ul className="tab-list">
                  <li
                    className="tab-item nav-item tab-item active"
                    data-filter="rotat_resid_meter_unmeter_one"
                  >
                    <label className="tab-trigger" htmlFor="tab1">
                      <h4>Metered</h4>
                    </label>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section class="rotating_section">
          <div class="info">
            <div class="bg_icon "></div>{" "}
            <span>
              {" "}
              Weigh the options of a metered plan with longer durations and
              traffic limits or unmetered plan with unlimited traffic but less
              IPs to optimize your proxy usage.
            </span>
          </div>
          <div class="container">
            <div class="rotatings_wrapper">
              <div class="rotating_card rotating_card_shadow active" id="card1">
                <div class="rotating_card_inner_con">
                  <div class="title blue">US | Rotating Mobile</div>
                  <div class="subtitle filter-item rotat_resid_meter_unmeter_one">
                    Metered
                  </div>
                  <div class="subtitle filter-item rotat_resid_meter_unmeter_two">
                    Unmetered
                  </div>
                  <div class="caption">
                    <span class="bold">Starts from</span>
                    {/* {} <div class="bg_icon icon_info tooltip"> */}
                    {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                    {/* </div> } */}
                  </div>
                  <div class="price_info">
                    <div class="price_plan">
                      <div class="dollar">$</div>
                      <div class="price">100</div>
                      <div class="plan">/Plan</div>
                    </div>
                  </div>
                  <div class="divider"></div>
                  <div class="list_info first">
                    <div class="caption">
                      <span>Origin of IPs</span>
                      {/* {} <div class="bg_icon icon_info tooltip"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span>United States</span>
                      <div class="bg_icon us"></div>
                    </div>
                  </div>
                  <div class="list_info ">
                    <div class="caption">
                      <span>IP Quantity</span>
                      {/* {} <div class="bg_icon icon_info tooltip"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span class="ips">200IPs</span>
                      <div class="bg_icon i-ps"></div>
                    </div>
                  </div>
                  <div class="list_info">
                    <div class="caption">
                      <span>Bandwidth</span>
                      {/* {} <div class="icon_info tooltip bg_icon"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span class="gig">5 GB</span>
                      <div class="bg_icon hard_drive"></div>
                    </div>
                  </div>
                  <div class="list_info">
                    <div class="caption">
                      <span>Plan Length</span>
                      {/* {} <div class="icon_info tooltip bg_icon"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span class="length_days">15 Days</span>
                      <div class="bg_icon calendar"></div>
                    </div>
                  </div>
                </div>
                <div class="select_wrapper">
                  <div class="select" tabindex="1"></div>
                  <div class="select_items"></div>
                </div>
                <div class="promo">
                  <div class="input_with_label">
                    <label for="promo" class="">
                      Have a promo code?
                    </label>
                    <div class="input_wrapper">
                      <input type="text" placeholder="Enter code" id="promo" />
                      <div class="input_button " data-href="#!">
                        Apply
                      </div>
                    </div>
                  </div>
                </div>
                <div class="btn buy_now buy_now1 active" data-href="#!">
                  Buy Now
                </div>
                <div class="bg_icon stripe_right"></div>
              </div>
              <div class="rotating_card rotating_card_shadow">
                <div class="rotating_card_inner_con">
                  <div class="title red">CA | Rotating Mobile</div>
                  <div class="subtitle filter-item rotat_resid_meter_unmeter_one">
                    Metered
                  </div>
                  <div class="subtitle filter-item rotat_resid_meter_unmeter_two">
                    Unmetered
                  </div>
                  <div class="caption">
                    <span class="bold">Starts from</span>
                    {/* {} <div class="bg_icon icon_info tooltip"> */}
                    {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                    {/* </div> } */}
                  </div>
                  <div class="price_info">
                    <div class="price_plan">
                      <div class="dollar">$</div>
                      <div class="price">0</div>
                      <div class="plan">/Plan</div>
                    </div>
                  </div>
                  <div class="divider"></div>
                  <div class="list_info first">
                    <div class="caption">
                      <span>Origin of IPs</span>
                      {/* {} <div class="bg_icon icon_info tooltip"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span>Canada</span>
                      <div class="bg_icon ca"></div>
                    </div>
                  </div>
                  <div class="list_info ">
                    <div class="caption">
                      <span>IP Quantity</span>
                      {/* {} <div class="bg_icon icon_info tooltip"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span class="ips">—</span>
                      <div class="bg_icon i-ps"></div>
                    </div>
                  </div>
                  <div class="list_info">
                    <div class="caption">
                      <span>Bandwidth</span>
                      {/* {} <div class="icon_info tooltip bg_icon"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span class="gig">—</span>
                      <div class="bg_icon hard_drive"></div>
                    </div>
                  </div>
                  <div class="list_info">
                    <div class="caption">
                      <span>Plan Length</span>
                      {/* {} <div class="icon_info tooltip bg_icon"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span class="length_days">—</span>
                      <div class="bg_icon calendar"></div>
                    </div>
                  </div>
                </div>
                <div class="select_wrapper">
                  <div class="select" tabindex="1"></div>
                  <div class="select_items"></div>
                </div>{" "}
                <div class="promo">
                  <div class="input_with_label">
                    <label for="promo" class="">
                      Have a promo code?
                    </label>
                    <div class="input_wrapper">
                      <input type="text" placeholder="Enter code" id="promo" />
                      <div class="input_button " data-href="#!">
                        Apply
                      </div>
                    </div>
                  </div>
                </div>
                <div class="btn buy_now buy_now2" data-href="#!">
                  Choose CA IPs
                </div>
                {/* {} <div class="bg_icon stripe_right"> */}
                {/* </div> } */}
              </div>
              <div class="rotating_card rotating_card_shadow">
                <div class="rotating_card_inner_con">
                  <div class="title purple">UK | Rotating Mobile</div>
                  <div class="subtitle filter-item rotat_resid_meter_unmeter_one">
                    Metered
                  </div>
                  <div class="subtitle filter-item rotat_resid_meter_unmeter_two">
                    Unmetered
                  </div>
                  <div class="caption">
                    <span class="bold">Starts from</span>
                    {/* {} <div class="bg_icon icon_info tooltip"> */}
                    {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                    {/* </div> } */}
                  </div>
                  <div class="price_info">
                    <div class="price_plan">
                      <div class="dollar">$</div>
                      <div class="price">0</div>
                      <div class="plan">/Plan</div>
                    </div>
                  </div>
                  <div class="divider"></div>
                  <div class="list_info first">
                    <div class="caption">
                      <span>Origin of IPs</span>
                      {/* {} <div class="bg_icon icon_info tooltip"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span>United Kingdom</span>
                      <div class="bg_icon uk"></div>
                    </div>
                  </div>
                  <div class="list_info ">
                    <div class="caption">
                      <span>IP Quantity</span>
                      {/* {} <div class="bg_icon icon_info tooltip"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span class="ips">—</span>
                      <div class="bg_icon i-ps"></div>
                    </div>
                  </div>
                  <div class="list_info">
                    <div class="caption">
                      <span>Bandwidth</span>
                      {/* {} <div class="icon_info tooltip bg_icon"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span class="gig">—</span>
                      <div class="bg_icon hard_drive"></div>
                    </div>
                  </div>
                  <div class="list_info">
                    <div class="caption">
                      <span>Plan Length</span>
                      {/* {} <div class="icon_info tooltip bg_icon"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span class="length_days">—</span>
                      <div class="bg_icon calendar"></div>
                    </div>
                  </div>
                </div>
                <div class="select_wrapper">
                  <div class="select" tabindex="1"></div>
                  <div class="select_items"></div>
                </div>
                <div class="promo">
                  <div class="input_with_label">
                    <label for="promo" class="">
                      Have a promo code?
                    </label>
                    <div class="input_wrapper">
                      <input type="text" placeholder="Enter code" id="promo" />
                      <div class="input_button " data-href="#!">
                        Apply
                      </div>
                    </div>
                  </div>
                </div>
                <div class="btn buy_now buy_now3" data-href="#!">
                  Choose UK IPs
                </div>
                <div class="bg_icon stripe_right popular"></div>
              </div>
              <div class="rotating_card rotating_card_shadow">
                <div class="rotating_card_inner_con">
                  <div class="title green">RL | Rotating Mobile</div>
                  <div class="subtitle filter-item rotat_resid_meter_unmeter_one">
                    Metered
                  </div>
                  <div class="subtitle filter-item rotat_resid_meter_unmeter_two">
                    Unmetered
                  </div>
                  <div class="caption">
                    <span class="bold">Starts from</span>
                    {/* {} <div class="bg_icon icon_info tooltip"> */}
                    {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                    {/* </div> } */}
                  </div>
                  <div class="price_info">
                    <div class="price_plan">
                      <div class="dollar">$</div>
                      <div class="price">0</div>
                      <div class="plan">/Plan</div>
                    </div>
                  </div>
                  <div class="divider"></div>
                  <div class="list_info first">
                    <div class="caption">
                      <span>Origin of IPs</span>
                      {/* {} <div class="bg_icon icon_info tooltip"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span>Random Location</span>
                      <div class="bg_icon ww"></div>
                    </div>
                  </div>
                  <div class="list_info ">
                    <div class="caption">
                      <span>IP Quantity</span>
                      {/* {} <div class="bg_icon icon_info tooltip"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span class="ips">—</span>
                      <div class="bg_icon i-ps"></div>
                    </div>
                  </div>
                  <div class="list_info">
                    <div class="caption">
                      <span>Bandwidth</span>
                      {/* {} <div class="icon_info tooltip bg_icon"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span class="gig">—</span>
                      <div class="bg_icon hard_drive"></div>
                    </div>
                  </div>
                  <div class="list_info">
                    <div class="caption">
                      <span>Plan Length</span>
                      {/* {} <div class="icon_info tooltip bg_icon"> */}
                      {/* <div class="tooltiptext">Lorem ipsum dolor sit amet consectetur </div> */}
                      {/* </div> } */}
                    </div>
                    <div class="details_right_icon">
                      <span class="length_days">—</span>
                      <div class="bg_icon calendar"></div>
                    </div>
                  </div>
                </div>
                <div class="select_wrapper">
                  <div class="select" tabindex="1"></div>
                  <div class="select_items"></div>
                </div>
                <div class="promo">
                  <div class="input_with_label">
                    <label for="promo" class="">
                      Have a promo code?
                    </label>
                    <div class="input_wrapper">
                      <input type="text" placeholder="Enter code" id="promo" />
                      <div class="input_button " data-href="#!">
                        Apply
                      </div>
                    </div>
                  </div>
                </div>
                <div class="btn buy_now buy_now4" data-href="#!">
                  Choose RL IPs
                </div>
                {/* {} <div class="bg_icon stripe_right"> */}
                {/* </div> } */}
              </div>
            </div>
          </div>
        </section>

        <Questions />
      </div>
      <Footer />
    </>
  );
}
